language: node_js

node_js:
  - '0.10'

branches:
  only:
    - master
    - travis-ci

before_install:
  - npm install
  - npm install istanbul coveralls

env:
  global:
  - secure: "RQ7a/aKmd00NAe/ugoordsu013KhhHaMIPzHn35nzVeqENesuzHTvtS3c1UgaZybVdsIer6dFVHQQPqwGJZ52n2e2wcVnvu+eGWTJSHFZN/NxiEQ00FkJm43v2h1Goc0BnVBd6dF7xJ3Qvntq/4x6evXj39orcEFI2Za1wHaxsg="
