language: node_js

node_js:
  - '0.10'

branches:
  only:
    - master
    - travis-ci

before_install:
  - npm install
  - npm install istanbul coveralls

env:
  global:
  - secure: A1A+zFTb/GWt0Wy7M8Vd9HISmV/rqPALdEzo/u2omcOKj9cY+zMzYHIiG/4z7yCeKy7XIL74FNNaBi+MvCqbMw8s5wgYEaIacFaog8ogHyOwKRb9QU/LOB1YQcdHyCMlrTrT8ODd510oiSCZTI0Lxha0gR4IlRdoq5ykUSIyZVM=
