#!/bin/sh

set -e

echo ""

(proof run t/*/*.t.js | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1

if [ "$TRAVIS" = "true" ] || [ "$MINIFY" = "true" ]; then
  echo "generating coverage"
  t/cover

  echo "submitting coverage to coveralls.io"
  cat coverage/lcov.info | node_modules/.bin/coveralls

  mkdir -p tmp/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
  cp -R coverage/* tmp/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
  (cd tmp && tar czvf ~/coverage.tar.gz $TRAVIS_REPO_SLUG)
  echo "$TRAVISTY_KEY" >> ~/.passphrase.txt
  gpg --passphrase-file ~/.passphrase.txt --decrypt t/id_travisty.gpg > ~/.ssh/id_travisty
  chmod 600 ~/.ssh/id_travisty
  cat t/known_hosts >> ~/.ssh/known_hosts
  ssh -i ~/.ssh/id_travisty alan@prettyrobots.com /home/alan/travisty < ~/coverage.tar.gz
fi

echo ""
